### ISSUE TITLE
Could not find config.dart file under example foulder

### ISSUE THREAD

**Issue by rakhimian** [peyter213/Flutter-Adal#1]

**Comment by MSchmack** [comment]
You have to serve your own configuration when testing the example. I am using gitignore to omit mine purposfully. It's a good point tho, I will try and add microsofts test ADFS Service to make the example work on one click.

Sorry for the late reply

**Comment by rakhimian** [comment]
Yes, it would be cool to add microsofts test ADFS Service. Thanks a lot!

**Comment by MSchmack** [comment]
I did not find a public test service by Microsoft so I created a Azure Active Directory, it also allows ADAL authentication. Config for testing is now added in the following commit 82613e0

**Comment by MSchmack** [comment]
I did not find a public test service by Microsoft so I created a Azure Active Directory, it also allows ADAL authentication. Config for testing is now added in the following commit 82613e0
